### PR TITLE
Use the request/response time not current Date.

### PR DESCRIPTION
**Pull request by praves77**
https://www.pivotaltracker.com/n/projects/1646401/stories/181425141.

"UTC based date + try/catch + Updated README.

### CODE REVIEW

**Comment by praves77** [comment]
This is a draft version for the feedback if my approach is correct. I have to cleanup log and use UTC.

**Review by dgilling — APPROVED** [review]
Looks good. Cleanup prints.

**Review by dgilling — APPROVED** [review]

**Review by keyur9 — APPROVED** [review]
lgtm. Have to update the version in the README.

**Comment by praves77** [comment]
@CodeYouMust @dgilling @keyur9 updated the PR to :
1. Use UTC
2. try/catch block around the code
3. Updated README

Unit tests passed.

**Pull request merged**
